# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Malayalam Comedy
email: contact@justinechacko.in
description: > # this means to ignore newlines until "baseurl:"
  Malayalam comedy videos
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fun.justinechacko.in" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
exclude: ["README.md"]
excerpt_separator: <!--more-->
sass:
    load_paths:
        - _sass
        - bs
paginate: 1
paginate_path: "page:num"
gems:
  - jekyll-paginate
  - jekyll-sitemap


